In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv(r"D:\Shrey\CETPA\Machine Learning\Data Sets\istanbul_stock_exchange.csv")
data.head(5)

date  TL BASED ISE  USD BASED ISE        SP       DAX      FTSE  \
0  5-Jan-09      0.035754       0.038376 -0.004679  0.002193  0.003894   
1  6-Jan-09      0.025426       0.031813  0.007787  0.008455  0.012866   
2  7-Jan-09     -0.028862      -0.026353 -0.030469 -0.017833 -0.028735   
3  8-Jan-09     -0.062208      -0.084716  0.003391 -0.011726 -0.000466   
4  9-Jan-09      0.009860       0.009658 -0.021533 -0.019873 -0.012710   

     NIKKEI   BOVESPA        EU        EM  
0  0.000000  0.031190  0.012698  0.028524  
1  0.004162  0.018920  0.011341  0.008773  
2  0.017293 -0.035899 -0.017073 -0.020015  
3 -0.040061  0.028283 -0.005561 -0.019424  
4 -0.004474 -0.009764 -0.010989 -0.007802

In [6]:
y = data.iloc[:,4].values
y

array([ 2.1934190e-03,  8.4553410e-03, -1.7833062e-02, -1.1726277e-02,
       -1.9872754e-02, -1.3525735e-02, -1.7673622e-02, -4.7383437e-02,
       -1.9550621e-02,  6.7907800e-03, -1.1549904e-02, -1.7833593e-02,
        5.0111860e-03, -9.8413990e-03, -9.6400520e-03,  3.4786791e-02,
       -7.9766100e-04,  4.4182012e-02, -2.0255911e-02, -2.0478765e-02,
       -1.5636734e-02,  2.4040020e-02,  2.6576513e-02,  3.9319050e-03,
        2.9305918e-02,  4.7661840e-03, -3.5170147e-02,  5.4340560e-03,
       -2.7420558e-02,  1.3218530e-03, -4.5613986e-02,  0.0000000e+00,
       -2.7643350e-03,  2.4346310e-03, -4.8746751e-02, -1.9673359e-02,
       -1.0393087e-02, -1.2797967e-02,  2.4757229e-02, -2.5399626e-02,
       -3.5395107e-02, -5.2291830e-03,  5.2829213e-02, -5.1537616e-02,
       -7.9001760e-03,  6.9634610e-03,  5.1456064e-02,  6.9529110e-03,
        1.0703606e-02, -6.6246800e-04,  2.2741267e-02, -1.4135646e-02,
        2.1417600e-03,  1.1726823e-02,  6.2326080e-03,  2.6109079e-02,
      

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)
x_train

array([[ 3.4066676e-02,  7.7092380e-03],
       [-7.7655400e-03, -1.0117621e-02],
       [-1.7984090e-02,  1.3032210e-02],
       [-1.6526020e-03,  1.9229060e-03],
       [ 5.8530750e-03,  1.6450715e-02],
       [-6.6432400e-04,  8.2657500e-04],
       [-2.0758160e-03,  2.4235670e-03],
       [-2.6864444e-02,  1.1672500e-04],
       [-7.4262540e-03,  5.8193230e-03],
       [ 2.4440981e-02,  8.3758440e-03],
       [-1.5515838e-02, -1.0882186e-02],
       [ 5.0912650e-03,  1.1533720e-03],
       [-5.2137420e-03,  6.3191210e-03],
       [-4.3677400e-03,  1.1459209e-02],
       [-3.5607494e-02, -5.3290700e-04],
       [-1.0003918e-02, -5.3348000e-04],
       [ 1.5539992e-02,  1.7254573e-02],
       [ 3.5347100e-03, -7.4966320e-03],
       [ 3.2506145e-02,  4.2289910e-03],
       [-2.9661366e-02,  0.0000000e+00],
       [ 1.9054811e-02, -1.1475674e-02],
       [-2.1593711e-02, -2.4127171e-02],
       [-3.1651660e-02, -1.2957720e-03],
       [ 2.9769540e-03,  1.1137931e-02],
       [-1.78413

In [8]:
#Standard Scaler performs the task of Standardization. 
#Usually a dataset contains variables that are different in scale.
s_c = StandardScaler()
x_train = s_c.fit_transform(x_train)
x_test = s_c.transform(x_test)
x_train

array([[ 1.56031820e+00,  5.14080131e-01],
       [-4.35155332e-01, -7.39013935e-01],
       [-9.22598935e-01,  8.88245014e-01],
       [-1.43556961e-01,  1.07344525e-01],
       [ 2.14477617e-01,  1.12854020e+00],
       [-9.64142857e-02,  3.02807041e-02],
       [-1.63745047e-01,  1.42537227e-01],
       [-1.34620813e+00, -1.96164102e-02],
       [-4.18970766e-01,  3.81233325e-01],
       [ 1.10115487e+00,  5.60937517e-01],
       [-8.04858781e-01, -7.92757102e-01],
       [ 1.78137881e-01,  5.32520745e-02],
       [-3.13429880e-01,  4.16365364e-01],
       [-2.73074031e-01,  7.77674879e-01],
       [-1.76326767e+00, -6.52806522e-02],
       [-5.41930073e-01, -6.53209298e-02],
       [ 6.76561349e-01,  1.18504537e+00],
       [ 1.03887348e-01, -5.54778127e-01],
       [ 1.48587801e+00,  2.69444950e-01],
       [-1.47962645e+00, -2.78212995e-02],
       [ 8.44224671e-01, -8.34474843e-01],
       [-1.09478449e+00, -1.72377990e+00],
       [-1.57456713e+00, -1.18904322e-01],
       [ 7.

In [9]:
model = SVC (kernel = 'linear',random_state = 1)
model.fit(x_train,y_train)
pred = model.predict(x_test)
pred

ValueError: Unknown label type: 'continuous'